### PR TITLE
add 3 create2 tests

### PR DESCRIPTION
**Pull request by mersinvald**

### CODE REVIEW

**Comment by whilei** [comment]
the only last thing i want to include assert before merge is that expected gas is correct, and show it’s derivation at least for documentation here

**Comment by whilei** [comment]
json s sûch a bummer, not allowing coments, for stuff like this

**Comment by mersinvald** [comment]
@whilei we can add documentation as a MarkDown file

**Comment by whilei** [comment]
So, `create2_0` -> 

```shell
code=0x6000600160006000f5600055
gas=0xbb68=47976
startgas=100000
gascost=startgas-gas=52024

# assemble from from
PUSH1 0x00  // 3
PUSH1 0x01  // 3 
PUSH1 0x00  // 3
PUSH1 0x00  // 3
CREATE2      // 32006
PUSH1 0x00 // 3
SSTORE       // 20000 // PTAL... there is a 3 missing here. Is that part of SSTORE's calculation,,,, _mem expansion!_ @mersinvald?

```

**Comment by mersinvald** [comment]
@whilei my calculations for 00.json are 52021


|gas  |opcode  |value  |
|:---:|:------:|:-----:|
|3    |PUSH1   |0x00   |
|3    |PUSH1   |0x01   |
|3    |PUSH1   |0x00   |
|3    |PUSH1   |0x00   |
|32006|CREATE2 |       |
|3    |PUSH1   |0x00   |
|20000|SSTORE  |       |

Total: 52021

**Comment by mersinvald** [comment]
And the actual consumed gas is 47976. So in both Sputnik and Geth there's a gas miscalculation bug or we're wrong in our estimation. Gonna check it out on Sputnik side.

**Pull request merged**
