### PR TITLE
Create2 VMTests

### PR DESCRIPTION
**Pull request by whilei**
- [x] 03: https://github.com/ETCDEVTeam/tests/commit/91980027190875f5222d9230bdb3d2956eb2fe66
- [x] 04: https://github.com/ETCDEVTeam/tests/pull/7/commits/1de6f26598b82a8d21f56d95253f15b9b8a1a1f6
- [x] 05
- [x] 06

### CODE REVIEW

**Comment by whilei** [comment]
https://github.com/ETCDEVTeam/tests/pull/7/commits/8f40daf38f12c4e639a5ef7a55e1e5cd49cd2000 seems obvious, now.

**Comment by mersinvald** [comment]
@whilei what do you think about removing non-runnable tests? 
It's causing issues in SVM, nothing unsolvable through refactoring, but are these necessary to have around?

**Comment by mersinvald** [comment]
Also I'm getting a lot of AccountCode check failures.

**Comment by mersinvald** [comment]
@whilei here's an example of error for 2_0. What is the output on geth? Do you check the account code?
```
Account code check failed for address 0x4d1a2e2bb4f88f0250f26ffff098b0b30b26bf38.
Expected: []
Actual:   [0]
```

**Comment by whilei** [comment]
@mersinvald Well caught; geth wasn't even checking those fields at all. See if https://github.com/ETCDEVTeam/tests/pull/7/commits/43ce9aa4e187de54150f14b9c10e6f32ce1b9821 fixes it for ya; seems to on geth side.

**Comment by mersinvald** [comment]
@whilei are you sure that `balance` value was invalid in tests? AFAIK, it should be identical to the `value` from the `exec` as that's the value passed to create that ought to be transferred to a newly created account.

Get the test failure on that too in svm, but here I'm not sure that it's a test-related issue.

**Comment by whilei** [comment]
> @whilei what do you think about removing non-runnable tests?
It's causing issues in SVM, nothing unsolvable through refactoring, but are these necessary to have around?
> https://github.com/ETCDEVTeam/tests/pull/7#issuecomment-433438405

Pros:
- matches EIP spec

Cons: 
- spec introduces unnecessary and useless complexity by prioritizing English dictionary word use in bytecode instead of actual runnable bytecode

Hm..

**Comment by whilei** [comment]
Aha -- again, this is geth's VMTests discriminating between VM/State domains; I'm assuming that's why `balance` and `code` were unchecked fields; because those values are assumed to be delegated to the `State` tests domain. Geth has a VM environment field set in this case to `skipTransfer=true`. 

You're right, though, that the vals should be transferred. Will revert.

**Comment by mersinvald** [comment]
@whilei so the tests are incorrect with the value. It's either should be no value transfer (0x0) or we should have the right value in the bytecode (currently it's 0x0 for 2_0 and should be the same as `value` field)

**Comment by whilei** [comment]
@mersinvald Not sure I see the mismatch you're mentioning?... (looking here: https://github.com/ETCDEVTeam/tests/pull/7/files?utf8=%E2%9C%93&diff=split&w=1#diff-8f26f65ba0e5ce7a04c27ba8c919a988R34)

Please go ahead and make any changes you see fitting --

**Comment by mersinvald** [comment]
@whilei okay, sure, will do.

**Comment by mersinvald** [comment]
Also I found out that tests do not check the code of the created contract.

**Comment by whilei** [comment]
@mersinvald With 55eaa9b, geth fails tests `03` and `04` with gas mismatches:

```
	vm2_test.go:109: create2_3 gas failed. Expected 47961, got 47967, diff=-6
		
	vm2_test.go:109: create2_4 gas failed. Expected 47961, got 47967, diff=-6
```

Here's the full debug from `03`:

```
2018/11/01 08:47:05 @ files/VMTests/ECIP1045/vmCreate2/03.json
2018/11/01 08:47:05 RunVM2 data: data= data.len=0
2018/11/01 08:47:05 evm.Run: caller=0x0000000000000000000000000000000000000000 input= code=6360de60ad60005260006004601c6000f5600055
2018/11/01 08:47:05 vm/Run.pc: op=PUSH4 cost=3 contract.gas=99997
2018/11/01 08:47:05 vm/Run.pc: op=PUSH1 cost=3 contract.gas=99994
2018/11/01 08:47:05 vm/Run.pc: op=MSTORE cost=6 contract.gas=99988
2018/11/01 08:47:05 vm/Run.pc: op=PUSH1 cost=3 contract.gas=99985
2018/11/01 08:47:05 vm/Run.pc: op=PUSH1 cost=3 contract.gas=99982
2018/11/01 08:47:05 vm/Run.pc: op=PUSH1 cost=3 contract.gas=99979
2018/11/01 08:47:05 vm/Run.pc: op=PUSH1 cost=3 contract.gas=99976
2018/11/01 08:47:05 newmemsize 32
2018/11/01 08:47:05 gas1 32000
2018/11/01 08:47:05 gas2 32006
2018/11/01 08:47:05 gas3 32006
2018/11/01 08:47:05 vm/Run.pc: op=CREATE2 cost=32006 contract.gas=67970
2018/11/01 08:47:05 opCreate2: off= 28 size= 4 input= 0x60de60ad salt= 0x0
2018/11/01 08:47:05 opCreate2: memory.data=0000000000000000000000000000000000000000000000000000000060de60ad
2018/11/01 08:47:05 cypto#CreateAddress2: addr=0x0000000000000000000000000000000000000000 salt=0000000000000000000000000000000000000000000000000000000000000000 init_code.len=32 init_code=f9f13700297b666e5636539d7d3e9189a13854c32618a4533f57f1ce13a7fb11
2018/11/01 08:47:05 cypto#CreateAddress2: createdAddr=0x0a2b4b8e17c1907899f8d66fc223d4596ba9a48f
2018/11/01 08:47:05 addr= 0x0a2b4b8e17c1907899f8d66fc223d4596ba9a48f
2018/11/01 08:47:05 vm/Run.pc: op=PUSH1 cost=3 contract.gas=67967
2018/11/01 08:47:05 vm/Run.pc: op=SSTORE cost=20000 contract.gas=47967
2018/11/01 08:47:05 vm/Run.pc: op=STOP cost=0 contract.gas=47967
2018/11/01 08:47:05 RunVm2: startgas=100000 endgas=47967 diffgas=52033
```

Can you see where Sputnik is spending the extra 6 gas?

----

EDIT:
This is because the expected gas wants to include the cost of running the CREATE2'd contract's `init_code` (PUSH_N_x2=6).

**Comment by mersinvald** [comment]
@whilei I removed the code depositing tests

**Review by mersinvald — APPROVED** [review]

**Pull request merged**
